site:
  name: LS Web Agency
  site: 'https://lswebagency.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: LS Web Agency
    template: '%s — LS Web Agency'
  description: "LS Web Agency realizza siti web professionali, eCommerce, SEO e strategie digitali per aziende e professionisti."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: LS Web Agency
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@lswebagency'
    site: '@lswebagency'
    cardType: summary_large_image

i18n:
  language: it
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/blog/%slug%' # SEO friendly per il blog
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'categoria' # Tradotto per la SEO italiana
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Percorso per i tag
      robots:
        index: true

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # Inserire ID di Google Analytics (es: "G-XXXXXXXXXX")

ui:
  theme: 'system' # Opzioni: "system" | "light" | "dark" | "light:only" | "dark:only"
